# Generated by Django 5.0.3 on 2024-03-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('starting_date', models.DateField(verbose_name='starting date')),
                ('deadline', models.DateField(verbose_name='dead line')),
            ],
        ),
        migrations.CreateModel(
            name='project_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertiseLevel', models.CharField(choices=[('BG', 'Beginner'), ('IN', 'Intermediate'), ('EX', 'Expert')], default='BG', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project', verbose_name='project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skills.skill', verbose_name='skill')),
            ],
        ),
        migrations.AddConstraint(
            model_name='project_skills',
            constraint=models.UniqueConstraint(fields=('project', 'skill'), name='unique project skill'),
        ),
    ]
