# Generated by Django 5.0.3 on 2024-03-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project_skills',
            new_name='Project_skill',
        ),
    ]
