# Generated by Django 5.0.3 on 2024-03-12 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertiseLevel', models.CharField(choices=[('BG', 'Beginner'), ('IN', 'Intermediate'), ('EX', 'Expert')], default='BG', max_length=2)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('skill', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skills.skill', verbose_name='skill')),
            ],
        ),
        migrations.AddConstraint(
            model_name='emp_skills',
            constraint=models.UniqueConstraint(fields=('employee', 'skill'), name='emp skill'),
        ),
    ]
