# Generated by Django 5.0.3 on 2024-03-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_emp_skills_emp_skills_emp_skill'),
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp_skills',
            new_name='Employee_skills',
        ),
    ]
