# Generated by Django 5.0.3 on 2024-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_rename_employee_skills_employee_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='blood_group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='contact_address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone_number'),
        ),
    ]
